export const USERS = [
  {
    nickname: 'Виктория',
    level: 12,
    coins: 45,
    vip: true,
    rank: 21,
    hasChest: true,
  },
  {
    nickname: 'Алексей',
    level: 9,
    coins: 30,
    vip: false,
    rank: 45,
    hasChest: false,
  },
  {
    nickname: 'Мария',
    level: 15,
    coins: 60,
    vip: true,
    rank: 12,
    hasChest: true,
  },
  {
    nickname: 'Ваш Никнейм',
    level: 10,
    coins: 120,
    vip: false,
    rank: 50,
    hasChest: false,
    isCurrentUser: true,
  },
  {
    nickname: 'Дмитрий',
    level: 7,
    coins: 5,
    vip: false,
    rank: 89,
    hasChest: false,
  },
  {
    nickname: 'Екатерина',
    level: 8,
    coins: 18,
    vip: false,
    rank: 76,
    hasChest: false,
  },
];