export enum AppRoute {
  Main = '/',
  Statistics = '/statistics',
  Integration = '/integrations/:integrationId',
  Tasks = '/tasks',
  Profile = '/profile',
  StrangerProfile = '/profile/:profileId',
  StrangerProfileRoom = '/profile/:profileId/room',
  Shop = '/shop',
  ShopInventory = '/shop/inventory',
  Promotion = '/promotion',
  Wardrobe = '/wardrobe',
  ProgressTree = '/progressTree',
  NotFound = '*',
}
