export const MODALS = {
  CREATING_INTEGRATION: 'creatingIntegration',
  CHANGING_NICKNAME: 'changingNickname',
  INVITE_FRIEND: 'inviteFriend',
  TOP_USERS: 'topUsers',
  SUBSCRIBE: 'subscribe',
  SUCCESSFULLY_SUBSCRIBED: 'successfullySubscribed',
  DAYS_IN_A_ROW: 'daysInARow',
  INTEGRATION_REWARD: 'integrationReward',
  GET_REWARD: 'getReward',
  TASK_COMPLETED: 'taskCompleted',
  TASK_CHEST: 'taskChest',
  STRANGER_PROFILE: 'strangerProfile',
  USERS_REFERRALS: 'usersReferrals',
  DAILY_TASKS: 'daily-tasks-modal',
  LOSS_PROGRESS: 'loss-of-progress',
  GET_GIFT: 'get-gift',
  NEW_ITEM: 'newItem',
  UPGRADED_ITEM: 'upgradedItem',
  UPGRADED_SHOP: 'upgradedShop',
  BINDING: 'binding',
  BINDING_CONFIRMATION: 'binding-confirmation',
  BINDING_SUCCESS: 'binding-success',
};
